using System.Data;
using System.Data.SqlClient;
using System;
using System.Collections.Generic;

namespace Ticketizer
{
    public class KAGenerator
    {
        public static List<Article> GenerateArticle()
        {
            List<Article> fakeNews = new List<Article>{};
            for(int i = 0; i< titleList.Count; i++)
            {
                string title = titleList[i];
                DateTime date = DateTime.Parse(dateList[i]);
                string content = texts[i];
                Article tempArticle = new Article(title, date, content);
                // tempArticle.Save();
                fakeNews.Add(tempArticle);
            }
            Console.WriteLine(titleList.Count);

            return fakeNews;
        }

        public static List<string> titleList = new List<string>
        {
            "Get achievements, play anywhere", "Games for this device", "Play and chat across devices", "Stream games and TV from your Xbox", "Record clips of PC games", "Play music with Groove", "Watch movies and TV shows", "Office apps in Windows 10", "Get started with Office 365", "Get help with Office"
        };
// data


        public static List<string> dateList = new List<string>
        {
            "2016-09-07", "2016-09-07", "2016-12-15", "2016-09-26", "2016-09-29", "2016-09-7", "2016-09-07", "2016-09-07", "2016-09-07", "2016-09-07"
        };


        public static List<string> texts = new List<string>
        {
            "Many of the same free and paid games are available across all Windows 10 devices—no matter which game is your favorite, chances are you can play it on any screen. When you're signed in to an Xbox Live-enabled game with your Microsoft account, your game progress saves to the cloud. If you're in the middle of a game on your Windows 10 phone and are interrupted, you can pick it up again later on your PC, right where you left off. Any achievements you pick up—for milestones in a game, or for special challenges—add to your total gamerscore, yours to keep. Compete on game leaderboards with your friends and people around the world on Xbox Live. To see the achievements, select Start Start symbol button, then select Xbox Image of Xbox logo. Select My games from the menu, choose the game, and then select Achievements. Pick individual achievements to see a brief description about how to unlock them.",
            "To get more games for your Windows 10 device, select the Start Start symbol button, then Store Windows Store logo, and then choose Games. You'll see games we picked for you, and a list of Top free games. Screenshot of Games page in the Windows Store. For a particular game or type of game, select Search  and type search terms such as racing games or card games, depending on what you're looking for. When you find a game you want, choose it, then select Free (if it's free) or Buy (if it's not free). Follow the instructions, and the game will automatically start downloading and installing on the device you're using. To play your game, select Play. To play it later, find all your games in the Xbox Image of Xbox logo app, in My games.",
            "Send messages. To send a message to friends on Xbox, select the Start Start symbol button, then select Xbox Image of Xbox logo. Sign in if you need to, and then select someone from your list of friends. Select Message  and type what you want to say. You can also invite them to a party by choosing Invite. Add friends. If you know a friend's gamertag, open the Xbox app and type your friend's gamertag in the Find people or clubs search box, then press Enter. Select Add friend  to add them as a friend on Xbox. To make new friends, we offer friend suggestions. Suggestions can include people you might already know on Xbox, or fellow gamers who make popular clips or broadcasts about games you like. To add a suggested friend to your list, choose their gamertag and select Add. Screenshot of find friends. Discover clubs and Looking for Group. Clubs are online meeting places for people to play and socialize. Join clubs that interest you or create a new club (your house, your rules). Think of Looking for Group as a “players wanted” bulletin board—a way to help you find players on Xbox Live. You can browse posts or create your own—when you've got enough people, start a party and play!",
            "Stream from your Xbox console to your PC to enjoy great console games and TV from the convenience of your PC. 1. Check your hardware. You’ll need a PC with at least a 1.5 GHz multicore processor and 4 GB of RAM, an Xbox One console, and a controller attached to your PC. To see system info, Select the Start Start symbol button, then select Settings  > System  > About . A wired Ethernet connection works best for streaming. If possible, connect both your PC and your Xbox One to your router using network cables. For a wireless connection, use an 802.11 N or newer wireless adapter. 2. Turn on streaming. On your Xbox One, go to Settings > Preferences > Game DVR & streaming. Check the box for Allow game streaming to other devices. Back up one level, to Settings > Preferences > SmartGlass connections. Select From any SmartGlass device to allow anyone who’s connected to your home network to stream games. To limit streaming to only a few people, select Only from profiles signed in on this Xbox. 3. Make the connection.  Turn on your Xbox One, and sign in with the same account you use to sign in to your PC. On your PC, start the Xbox app. Select Connect from the Xbox app menu, then select the Xbox console you want to connect to. Next time, the Xbox app will connect to your Xbox One automatically.  Screenshot of streaming settings. 4. Time to play! Once you’re connected to your console, select Stream and choose OneGuide for TV, or the game you want to play. Or, choose an Xbox One game anywhere in the app, and then select Play from console to stream it.",
            "Windows 10 helps you take screenshots and record clips of PC games with built-in recording—no extra gear to buy! Capture your moment of glory, then share it with your friends on social networks and Xbox Live. Screenshot of Game bar. Record what just happened. To set up to capture moments during play, launch your game, then press the Windows logo key Windows key logo + G on your keyboard to open Game bar. Select Settings  and then select Record game in the background. With Game bar running in the background, press the Windows logo key Windows key logo + Alt + G. The last 30 seconds of gameplay will be saved as a game clip. Record what's happening. Something awesome happens in a game, press the Windows logo key Windows key logo + Alt + R to start a recording, then press it again to stop recording. You'll see the screen flash when the recording starts and ends. If these shortcuts don't work, go to the game's settings and look for an option to run the game in a window. Once it's running in a window, press the Windows logo key Windows key logo + G and select Yes, this is a game. You should be able to use the shortcuts when the game is full-screen again. Trim to the best parts. After you record a clip, highlight the best parts or focus on a particular moment by trimming it in the Xbox app. Open the Xbox app, and select Game DVR. Everything you record using Game bar is listed under On this PC. Screenshot of Game bar. Share it with the world. When your clip or screenshot is the way you want it in Game DVR, select Share to upload it to Xbox Live, so friends and other people can enjoy it (based on your privacy settings). You'll also see your shared stuff when you sign in to Xbox on other devices. To share your clips and screenshots on other networks, select Open folder to see all your captures. Upload these files to your favorite social networks or send them directly to friends.",
            "Enjoy all the music you love in one simple, fast, and elegant Windows 10 app. By itself, Groove makes it easy to play and manage your music and playlists. But when you add your songs to , Groove lets you play them—for free—on all your favorite devices: PC, Xbox, Android, iPhone, Windows phone, Sonos, and the web. On your PC, just add your MP3s, even iTunes songs, to your music folder on OneDrive. Then you’ll have them at your fingertips in Groove on any of your devices. Want more ways to play? Get a Groove Music Pass and dive into artist-based radio, curated playlists, and one of the biggest music catalogs on the planet. Groove Music Pass lets you stream and download new hits and familiar favorites from a selection of over 40 million songs. Listen—ad-free—just about anywhere.",
            "Rent and buy the latest hit movies and commercial-free TV shows from Microsoft, and watch them using the Movies & TV app—at home or on the go. At the Windows Store, choose from a huge selection of films in 1080p HD in a variety of genres. The Store also features commercial-free TV shows the day after they air on broadcast networks. Buy single episodes, or buy a season pass to get the latest shows automatically delivered to the Movies & TV app on all of your Microsoft devices (Windows PC, Xbox, Windows phone, or Windows tablet). Watch at home or on the go. Need to watch the latest programs right now? If you have a broadband connection, stream to watch instantly. Travelling? Download to your Windows laptop, tablet, or phone, and enjoy it on the road, even without Internet. Play the same movie on your phone and tablet, and pick up where you left off. All of your purchased movies and TV shows are stored online and synced across the devices you use with your Microsoft account, so your programs follow you from screen to screen. Start a movie on your Windows tablet while riding the bus, then finish it on your TV at home using Xbox. The Movies & TV app makes it easy to pick up where you left off.",
            "Whether you need to find Office on your Windows 10 PC install an old version on Windows 10, or get a new version of Office, we'll show you what to do. Already have Office? Search for Office apps by name in the search box on the taskbar to find them. For example, type word or excel. Search for installed Office apps. Notes: To transfer Office from an old computer to a new one, uninstall it from the old computer first. Then install it on the new one and use the same product key when you're prompted for activation. For more about product keys, see this topic on Office 2013 and Office 2016, or this topic on Office 2010. Office 2007 and earlier aren't compatible with Windows 10. Don't have Office yet? We recommend starting with a free trial of Office 365, a subscription that includes the Office apps, subscriber-only features, and online services like 1 TB of OneDrive storage. If you'd rather not subscribe, you can still make a one-time purchase of Office. See Choose your Office to learn more. Office on touch-enabled Windows 10 devices. On a Windows 10 PC with a touchscreen, you might prefer the Office Mobile apps: pared-down versions optimized for touch; no keyboard or mouse required. Go to the Windows Store and search for office. You'll find familiar apps like Word Mobile, Excel Mobile, and PowerPoint Mobile, as well as newer arrivals like Sway. (OneNote, OneDrive, Mail, and Calendar are already installed on Windows 10.)",
            "Office 365 is a subscription service that includes the Office apps you're familiar with, including Word and Excel, which you can install on a combination of up to 15 devices—PC, Mac, tablet, or phone. A subscription also includes perks like oodles of cloud storage and monthly feature updates. Try it free for a month. The Office 365 apps. If you've already got an Office 365 subscription, you'll need your Microsoft account to log in and install the Office apps or to change your billing or other aspects of your subscription. And here's more help, in case you need it—where to sign in, how to install the Office apps, and how to find your apps after you've installed them.",
            "If you want to learn what's new with Office apps or how to use them, visit Office help and training. Having trouble using Office with Windows 10? Check out this list of known issues with Office and. If you're having problems with a specific Office app, like Outlook or Word, see these fixes or workarounds for issues in Office apps."
        };
    }


}
