using System.Data;
using System.Data.SqlClient;
using System;
using System.Collections.Generic;

namespace Ticketizer
{
    public class KAGenerator
    {
        public static List<Article> GenerateArticle()
        {
            List<Article> fakeNews = new List<Article>{};
            for(int i = 0; i< titleList.Count; i++)
            {
                string title = titleList[i];
                DateTime date = DateTime.Parse(dateList[i]);
                string content = texts[i];
                Article tempArticle = new Article(title, date, content);
                // tempArticle.Save();
                fakeNews.Add(tempArticle);
            }
            Console.WriteLine(titleList.Count);

            return fakeNews;
        }

        public static List<string> titleList = new List<string>
        {
            "Get achievements, play anywhere", "Games for this device", "Play and chat across devices", "Stream games and TV from your Xbox", "Record clips of PC games", "Play music with Groove", "Watch movies and TV shows", "Office apps in Windows 10", "Get started with Office 365", "Get help with Office", "Choose your Office", "Set up your family", "Keep your PC up to date", "Find settings", "Get started with themes",
            "Change desktop background and colors", "Find your notifications", "Lock screen features", "Personalize your lock screen", "OneDrive on your PC"
        };
// data


        public static List<string> dateList = new List<string>
        {
            "2016-09-07", "2016-09-07", "2016-12-15", "2016-09-26", "2016-09-29", "2016-09-7", "2016-09-07", "2016-09-07", "2016-09-07", "2016-09-07", "2017-01-17", "2016-09-16", "2016-09-29", "2016-09-07", "2016-09-07", "2016-09-29", "2016-09-29", "2016-09-07", "2016-09-29", "2016-09-26"
        };


        public static List<string> texts = new List<string>
        {
            "Many of the same free and paid games are available across all Windows 10 devices—no matter which game is your favorite, chances are you can play it on any screen. When you're signed in to an Xbox Live-enabled game with your Microsoft account, your game progress saves to the cloud. If you're in the middle of a game on your Windows 10 phone and are interrupted, you can pick it up again later on your PC, right where you left off. Any achievements you pick up—for milestones in a game, or for special challenges—add to your total gamerscore, yours to keep. Compete on game leaderboards with your friends and people around the world on Xbox Live. To see the achievements, select Start Start symbol button, then select Xbox Image of Xbox logo. Select My games from the menu, choose the game, and then select Achievements. Pick individual achievements to see a brief description about how to unlock them.",
            "To get more games for your Windows 10 device, select the Start Start symbol button, then Store Windows Store logo, and then choose Games. You'll see games we picked for you, and a list of Top free games. Screenshot of Games page in the Windows Store. For a particular game or type of game, select Search  and type search terms such as racing games or card games, depending on what you're looking for. When you find a game you want, choose it, then select Free (if it's free) or Buy (if it's not free). Follow the instructions, and the game will automatically start downloading and installing on the device you're using. To play your game, select Play. To play it later, find all your games in the Xbox Image of Xbox logo app, in My games.",
            "Send messages. To send a message to friends on Xbox, select the Start Start symbol button, then select Xbox Image of Xbox logo. Sign in if you need to, and then select someone from your list of friends. Select Message  and type what you want to say. You can also invite them to a party by choosing Invite. Add friends. If you know a friend's gamertag, open the Xbox app and type your friend's gamertag in the Find people or clubs search box, then press Enter. Select Add friend  to add them as a friend on Xbox. To make new friends, we offer friend suggestions. Suggestions can include people you might already know on Xbox, or fellow gamers who make popular clips or broadcasts about games you like. To add a suggested friend to your list, choose their gamertag and select Add. Screenshot of find friends. Discover clubs and Looking for Group. Clubs are online meeting places for people to play and socialize. Join clubs that interest you or create a new club (your house, your rules). Think of Looking for Group as a “players wanted” bulletin board—a way to help you find players on Xbox Live. You can browse posts or create your own—when you've got enough people, start a party and play!",
            "Stream from your Xbox console to your PC to enjoy great console games and TV from the convenience of your PC. 1. Check your hardware. You’ll need a PC with at least a 1.5 GHz multicore processor and 4 GB of RAM, an Xbox One console, and a controller attached to your PC. To see system info, Select the Start Start symbol button, then select Settings  > System  > About . A wired Ethernet connection works best for streaming. If possible, connect both your PC and your Xbox One to your router using network cables. For a wireless connection, use an 802.11 N or newer wireless adapter. 2. Turn on streaming. On your Xbox One, go to Settings > Preferences > Game DVR & streaming. Check the box for Allow game streaming to other devices. Back up one level, to Settings > Preferences > SmartGlass connections. Select From any SmartGlass device to allow anyone who’s connected to your home network to stream games. To limit streaming to only a few people, select Only from profiles signed in on this Xbox. 3. Make the connection.  Turn on your Xbox One, and sign in with the same account you use to sign in to your PC. On your PC, start the Xbox app. Select Connect from the Xbox app menu, then select the Xbox console you want to connect to. Next time, the Xbox app will connect to your Xbox One automatically.  Screenshot of streaming settings. 4. Time to play! Once you’re connected to your console, select Stream and choose OneGuide for TV, or the game you want to play. Or, choose an Xbox One game anywhere in the app, and then select Play from console to stream it.",
            "Windows 10 helps you take screenshots and record clips of PC games with built-in recording—no extra gear to buy! Capture your moment of glory, then share it with your friends on social networks and Xbox Live. Screenshot of Game bar. Record what just happened. To set up to capture moments during play, launch your game, then press the Windows logo key Windows key logo + G on your keyboard to open Game bar. Select Settings  and then select Record game in the background. With Game bar running in the background, press the Windows logo key Windows key logo + Alt + G. The last 30 seconds of gameplay will be saved as a game clip. Record what's happening. Something awesome happens in a game, press the Windows logo key Windows key logo + Alt + R to start a recording, then press it again to stop recording. You'll see the screen flash when the recording starts and ends. If these shortcuts don't work, go to the game's settings and look for an option to run the game in a window. Once it's running in a window, press the Windows logo key Windows key logo + G and select Yes, this is a game. You should be able to use the shortcuts when the game is full-screen again. Trim to the best parts. After you record a clip, highlight the best parts or focus on a particular moment by trimming it in the Xbox app. Open the Xbox app, and select Game DVR. Everything you record using Game bar is listed under On this PC. Screenshot of Game bar. Share it with the world. When your clip or screenshot is the way you want it in Game DVR, select Share to upload it to Xbox Live, so friends and other people can enjoy it (based on your privacy settings). You'll also see your shared stuff when you sign in to Xbox on other devices. To share your clips and screenshots on other networks, select Open folder to see all your captures. Upload these files to your favorite social networks or send them directly to friends.",
            "Enjoy all the music you love in one simple, fast, and elegant Windows 10 app. By itself, Groove makes it easy to play and manage your music and playlists. But when you add your songs to , Groove lets you play them—for free—on all your favorite devices: PC, Xbox, Android, iPhone, Windows phone, Sonos, and the web. On your PC, just add your MP3s, even iTunes songs, to your music folder on OneDrive. Then you’ll have them at your fingertips in Groove on any of your devices. Want more ways to play? Get a Groove Music Pass and dive into artist-based radio, curated playlists, and one of the biggest music catalogs on the planet. Groove Music Pass lets you stream and download new hits and familiar favorites from a selection of over 40 million songs. Listen—ad-free—just about anywhere.",
            "Rent and buy the latest hit movies and commercial-free TV shows from Microsoft, and watch them using the Movies & TV app—at home or on the go. At the Windows Store, choose from a huge selection of films in 1080p HD in a variety of genres. The Store also features commercial-free TV shows the day after they air on broadcast networks. Buy single episodes, or buy a season pass to get the latest shows automatically delivered to the Movies & TV app on all of your Microsoft devices (Windows PC, Xbox, Windows phone, or Windows tablet). Watch at home or on the go. Need to watch the latest programs right now? If you have a broadband connection, stream to watch instantly. Travelling? Download to your Windows laptop, tablet, or phone, and enjoy it on the road, even without Internet. Play the same movie on your phone and tablet, and pick up where you left off. All of your purchased movies and TV shows are stored online and synced across the devices you use with your Microsoft account, so your programs follow you from screen to screen. Start a movie on your Windows tablet while riding the bus, then finish it on your TV at home using Xbox. The Movies & TV app makes it easy to pick up where you left off.",
            "Whether you need to find Office on your Windows 10 PC install an old version on Windows 10, or get a new version of Office, we'll show you what to do. Already have Office? Search for Office apps by name in the search box on the taskbar to find them. For example, type word or excel. Search for installed Office apps. Notes: To transfer Office from an old computer to a new one, uninstall it from the old computer first. Then install it on the new one and use the same product key when you're prompted for activation. For more about product keys, see this topic on Office 2013 and Office 2016, or this topic on Office 2010. Office 2007 and earlier aren't compatible with Windows 10. Don't have Office yet? We recommend starting with a free trial of Office 365, a subscription that includes the Office apps, subscriber-only features, and online services like 1 TB of OneDrive storage. If you'd rather not subscribe, you can still make a one-time purchase of Office. See Choose your Office to learn more. Office on touch-enabled Windows 10 devices. On a Windows 10 PC with a touchscreen, you might prefer the Office Mobile apps: pared-down versions optimized for touch; no keyboard or mouse required. Go to the Windows Store and search for office. You'll find familiar apps like Word Mobile, Excel Mobile, and PowerPoint Mobile, as well as newer arrivals like Sway. (OneNote, OneDrive, Mail, and Calendar are already installed on Windows 10.)",
            "Office 365 is a subscription service that includes the Office apps you're familiar with, including Word and Excel, which you can install on a combination of up to 15 devices—PC, Mac, tablet, or phone. A subscription also includes perks like oodles of cloud storage and monthly feature updates. Try it free for a month. The Office 365 apps. If you've already got an Office 365 subscription, you'll need your Microsoft account to log in and install the Office apps or to change your billing or other aspects of your subscription. And here's more help, in case you need it—where to sign in, how to install the Office apps, and how to find your apps after you've installed them.",
            "If you want to learn what's new with Office apps or how to use them, visit Office help and training. Having trouble using Office with Windows 10? Check out this list of known issues with Office and. If you're having problems with a specific Office app, like Outlook or Word, see these fixes or workarounds for issues in Office apps.",
            "Confused about the differences between Office products, and which one is right for you? Here's a quick overview to help you sort it all out. Office 2016. Office 2016 is the latest version of the product you're probably most familiar with: the suite of productivity apps (like Word, Excel, and PowerPoint) that you buy once and install on your PC. Used an older version Office before? See what's new and improved in Office 2016. The Office 365 apps. Note. Office 2016 doesn't have an upgrade option, so if you plan to upgrade to the next major release of Office, you'll have to buy it at full price. Office 365. Office 365 is a subscription service that always gives you access to the most recent version of Office (currently Office 2016). A subscription also gives you additional benefits, like extra online storage and ongoing tech support. Plus, you get updates and new features as they're released. When the next version of Office is released, your Office 365 subscription lets you upgrade at no additional cost. See what's new and improved in Office 2016 for Office 365. Still not sure which version to get? Compare Office plans and pricing. Office Online. Office Online is the free version of Office that you can use in your web browser. Try the Office Online apps. Just want Word or Excel? You can still buy standalone versions of the Office apps, including Word, Excel, and PowerPoint. Go to the Microsoft Store and search for the Office app you want.",
            "Family makes it faster than ever to add family members to each Windows 10 PC you sign in to with your Microsoft account. Family also lets adults keep kids stay safer online. Adults in the family can see reports of kids’ online activity, limit how long and when kids use their Windows 10 devices, set smart limits on kids’ spending, and help make sure kids don't see inappropriate websites, apps, or games. If you used Family Safety on an earlier version of Windows, you’ll need to add your family members again for kids’ settings to apply on Windows 10 devices. Adults in the family can manage family settings online at account.microsoft.com/family, and changes will be applied to any Windows 10 device the child signs in to. To set up a PC for people already in your Microsoft family, select the Start Start symbol button, then select Settings  > Accounts  > Family & other users. Select their accounts to add them to this PC. The first time they sign in, they’ll need to enter the password for their Microsoft account. Add someone to your family. On your Windows 10 PC, select the Start Start symbol button, then select Settings  > Accounts  > Family & other people. (You'll need to be signed in to Windows with a Microsoft account.) Select Add a family member. Select Add a child or Add an adult. Type the email address of the person to send them an invitation to join. If they don't have an email address, select The person I want to invite doesn’t have an email address and follow the directions to set up a new account. After they've accepted the email invitation, have them sign in to Windows 10 using the same email address you sent the invitation to. Screen showing the Accounts screen where you can add a family member. Manage family settings. After you've added a child to your family on Windows, here's how you manage their activity. Go to account.microsoft.com/family and sign in with your Microsoft account. Select the child whose settings you want to manage from the list of children in your Family. If your kids also use Family Safety on older versions of Windows, or My Family on older Windows phones, you’ll see them listed per device. Choose what to turn on or change for your child's account: Recent activity allows you to see what websites they've been visiting, what apps and games they've been using, and how much time they've been spending on their devices. Web browsing lets you choose what websites your child can and can't see. Apps & games allows you to limit the apps and games your child can download from the Windows Store. It also lets you unblock any app or game you’ve blocked previously. Screen time allows you to set the maximum amount of time they can spend on their devices.",
            "Print We've made it easier to keep Windows current with the latest features and improvements—and with fewer interruptions and restarts when you're using your PC the most. The great news is that you don’t have to do anything to get the latest updates, as they'll automatically download and install when they’re available. (Unless you’re on a metered connection, then updates won’t download until you get them.) Occasionally, your PC may need to restart to finish installing the updates. You can set active hours to let us know when you're usually using your PC to help prevent inconvenient restarts. Select the Start Start symbol button, then select Settings  > Update & security  > Windows Update, and then select Change active hours. Screenshot of dialog window for changing active hours. Choose the start time and end time for active hours, and then select Save.",
            "Find your Windows settings in a snap! Image for finding settings. Select the Start Start symbol button, then select Settings . From there, browse the categories or use search to find what you're looking for. Most apps have their own settings—look for this icon  in the app.",
            "Select the Start Start symbol button, then select Settings  > Personalization > Themes > Theme settings. Then choose from a default theme, or select Get more themes online to download new themes featuring cute critters, holiday cheer, and other smile-inducing options.",
            "Select the Start Start symbol button, then select Settings  > Personalization to choose a picture worthy of gracing your desktop background, and to change the accent color for Start, the taskbar, and other items. The preview window gives you a sneak peek of your changes as you make them. In Background, select a picture or solid color, or create a slideshow of pictures. Desktop background personalization settings. In Colors, let Windows pull an accent color from your background, or choose your own color adventure. Accent colors in personalization settings. After you've selected an accent color, decide where you want to see it show up, and whether it looks better in a dark or light setting.",
            "Windows 10 puts notifications and quick actions in action center—right on the taskbar—where you can get to them instantly. To open action center from the taskbar, select the action center icon . (You can also swipe in from the right edge of your screen, or press Windows logo key Start symbol+A.)  Action center. Notifications at a glance. If a notification has an arrow to the right, select the arrow to read more or take action—like replying to a message—without having to open the related app or other notification sender. Don't want to take any action? Clear the notification by selecting and dragging it off screen to the right, or by selecting the clear  button. Want to see notifications from some apps before others in action center? Press and hold (or right-click) a notification group's name and select Make this group high priority. Notifications from high-priority senders always appear above notifications from normal-priority senders. Notifications in action center. Take a shortcut. Quick actions take you right to the settings and apps you're likely to use often, from Bluetooth to brightness. When you open action center you'll see all your available quick actions. Collapse them to see only your top picks.",
            "Just because your Windows device is locked doesn't mean it's only good for a pretty picture. There's still lots you can do from the lock screen. Talk to Cortana. Cortana can still answer your burning questions, from the straightforward ('What's the weather forecast?') to the silly ('Do you like cats?')—not to mention setting reminders and checking your calendar. Cortana on lock screen. To allow Cortana on your lock screen, select the search box on the taskbar. From there, select Settings  and turn on Let Cortana respond to 'Hey Cortana' and Use Cortana even when my device is locked. Cortana on lock screen. Note. For sensitive tasks and opening apps, Cortana will still protect your info by prompting you to unlock your device. Play music. Music lovers can see what's playing on the lock screen and control the action from start to stop. To try it out, play music from Groove or another music app, then press the Windows logo key + L  Start symbol to go to the lock screen.",
            "To tweak your lock screen to your liking, select the Start Start symbol button, then select Settings  > Personalization  > Lock screen. Try changing the background to a favorite photo or slide show, or choose any combination of detailed and quick status notifications to show you upcoming calendar events, social network updates, and other app and system notifications.",
            "OneDrive is free online storage that comes with your Microsoft account. Save your files there and you'll be able to get to them from any PC, tablet, or phone. The basics. To save a doc you're working on to OneDrive, select a OneDrive folder from the list of save locations. To move files to OneDrive, open File Explorer and then drag them into a OneDrive folder. Screenshot of SkyDrive File being dragged into a SkyDrive folder. No Internet? No problem. Files you save to OneDrive are available online at OneDrive.com and offline on your PC. That means you can use them anytime, even when you're not connected to the Internet. When you reconnect, OneDrive updates the online versions with changes you made offline. Offline files come in handy when you're stuck without Wi-Fi, but they also take up space on your PC. If you're running low on storage space, here's how to keep fewer OneDrive files offline: Stay in sync. File Explorer icons show you the sync status of your offline folders and files. Image of sync icon It's in sync with online version. Image of syncing icon It's getting in sync. Image of out-of-sync icon The version on your PC is out of sync. To find out why, go to the right side of the taskbar, select the Show hidden icons arrow, press and hold (or right-click) OneDrive OneDrive icon, and then select View sync problems. At the Office. Learn how to create and share Office docs through the OneDrive website—and get the apps that can sync and edit docs on the go—in the Get started with OneDrive eBook."
        };
    }


}
